name: Validate PR on develop branch
on: 
  pull_request:
    types: [opened, synchronize]
    branches: [development]
    paths:
      - 'force-app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run script
      run: echo Hello Man
    - name: Run many scripts
      run: |
        echo I am here
        echo I am here again 